a=int(input("ingrese n1"))
b=int(input("ingrese D1"))
c=int(input("ingrese n2"))
d=int(input("ingrese D2"))
suma=(a*d+b*c)
sumadeno=(b*d)
resultado=suma/sumadeno
print("resultado suma:", resultado)
resta=(a*d-b*c)
restadeno=(b*d)
resultador=resta/restadeno
print("resultado resta:", resultador)
multi=(a*c)
multideno=(b*d)
resultadoM=(multi/multideno)
print("resultado multi:", resultadoM)
divi=(a*d)
divideno=(b*c)
resultadoD=(divi/divideno)
print("resultado divi:", resultadoD)